// The game's files as Apple shipped them: what must be present, and intact, before the game
// runs. The table itself is generated by tools/manifest.py from a known-good copy.
#pragma once

#include <cstddef>
#include <cstdint>

namespace minigolf::gamedata {

struct ManifestEntry {
    const char* path;  // relative to the game directory, '/'-separated
    uint32_t size;
    uint32_t crc32;
};

extern const ManifestEntry GAME_MANIFEST[];
extern const size_t GAME_MANIFEST_SIZE;

// The game directory's name on the iPod, and the image inside it.
constexpr const char* GAME_DIRECTORY_NAME = "88888";
// And what the same folder is called in the copy people actually get hold of: iTunes packaged
// each game as an `.ipg`, which is a zip with the game's *display* name at the top rather than
// its number. Somebody carrying the folder across by hand — which is the only way to do it on a
// handheld — has this one, and renaming it is a step that is easy to forget and, from inside the
// game, indistinguishable from not having the files at all. So both names are looked for.
constexpr const char* GAME_DIRECTORY_ALIAS = "Mini Golf";
constexpr const char* GAME_IMAGE_PATH = "Executables/Minigolf_1_1_2563296.bin";

}  // namespace minigolf::gamedata
